export const creamStyles = {
  colors: {
    bgPrimary: '#F4EEE3',
    bgSurface: '#FBF7EF',
    bgSurfaceHover: '#F3ECE0',
    textPrimary: '#3B3426',
    textSecondary: '#7A7060',
    border: '#DED4C2',
    accent: '#C2693F',
    accentHover: '#A5542F',
    accentLight: '#F3DCC7',
    success: '#5E9B6B',
    successBg: '#E4F0E2',
    successBorder: '#C2D9BC',
    warning: '#D9A13B',
    warningBg: '#FAF0D3',
    warningBorder: '#EBDCA8',
    error: '#C2453E',
    errorHover: '#A53A34',
    errorBg: '#F8E2DE',
    errorBorder: '#EBBCB6',
  },
};