export const lightStyles = {
  colors: {
    bgPrimary: '#E9EDE9',
    bgSurface: '#F7F9F7',
    bgSurfaceHover: '#ECEFEC',
    textPrimary: '#1A1F1C',
    textSecondary: '#646D68',
    border: '#CFD6D0',
    accent: '#21A038',
    accentHover: '#1A8630',
    accentLight: '#DFF3E2',
    success: '#1E9E57',
    successBg: '#E2F5EA',
    successBorder: '#BCE5CD',
    warning: '#E8A200',
    warningBg: '#FFF4D6',
    warningBorder: '#F5DCA8',
    error: '#D92B2B',
    errorHover: '#B81F1F',
    errorBg: '#FCE4E4',
    errorBorder: '#F4B8B8',
  },
};
